=head1 NAME

wolf (=work on latex file) provides a simple LaTeX IDE.

=head1 DESCRIPTION

similar to latexmk, this program compiles a latex file to pdf using 'pdflatex' and 
'bibtex' everytime the latex file or bibtex file or included files change.
Additionally this tool opens your favourite latex editor and your favourite 
viewer automatically.
At the end of compiling a summary of all errors and warnings is printed.

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/wolf
